# Generated by Django 2.2.6 on 2019-11-10 05:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30)),
                ('marca', models.CharField(max_length=30)),
                ('precio', models.IntegerField(validators=[django.core.validators.MaxValueValidator(99999)])),
                ('imagen', models.ImageField(upload_to='')),
                ('descripcion', models.TextField(max_length=100)),
            ],
        ),
    ]
