# Generated by Django 2.2.6 on 2019-11-13 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0002_auto_20191110_0229'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'permissions': (('admin', 'Es administrador'), ('cliente', 'Es cliente'))},
        ),
    ]
