# Generated by Django 2.2.6 on 2019-11-25 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0006_extendeduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='edad',
            field=models.DateField(),
        ),
    ]
